line-length = 100
indent-width = 4


target-version = "py312"


src =       [   
                "src/"
            ]


exclude =   [
                "docs/*",
                "venv/*",
            ]


include =   [
                "main.py"
            ]


[format]
docstring-code-format = true
docstring-code-line-length = 80
skip-magic-trailing-comma = false
indent-style = "space"
line-ending = "lf"
quote-style = "double"



[lint]
select =    [
                "E", # pycodestyle errors
                "F", # Pyflakes errors
                "I", # Import sorting (isort)
                "D", # Docstring rules
                "N", # Naming conventions (PEP 8)
                "UP", # Modernize code (pyupgrade)
                "B", # Possible errors (bugbear)
                "RUF", # Ruff-specific rules
                "PIE", # More Pythonic code (flake8-pie)
                "ARG", # Unused arguments (flake8-unused-arguments)
                "TCH", # Type checking conventions (flake8-type-checking)
                "ASYNC", # Rules for asyncio (flake8-async),
                "FAST" # FastAPI rules (FAST)
            ]


ignore =    [
                "D212",  # Ignore "multi-line-summary-first-line" (preferring D213)
                "D211",  # Ignore "no-blank-line-before-class" (preferring D203)
                "D203",  # Ignore "one-blank-line-after-class-definition" (conflict with formatter)
            ]


[lint.per-file-ignores]
"__init__.py" = ["D104"]
"src/presentation/api/**/*.py" = ["B008"]